In [1]:
import pandas as pd
import math

import pandas.io.sql as pd_sql
import psycopg2 as pg
from sqlalchemy import create_engine

# psychopg connection parameters
params = {'user': 'postgres', 'host': 'localhost', 'port': 5432, 'password': None}
connection = pg.connect(**params, dbname='mountain_project') # Connect
cursor = connection.cursor()

# sqlalchemy connection arguments
connection_str = f'postgres://postgres:{None}@localhost:5432/mountain_project'
engine = create_engine(connection_str)

In [2]:
buttermilks_scrape_df = pd.read_csv(r"data/scraped-data/buttermilks-scrape.csv")
buttermilks_scrape_df[['url', 'star_ratings', 'suggested_ratings', 'on_to_do_lists', 'ticks']].to_sql('buttermilks_scrape', engine, index=True) # Create the database

druid_stones_scrape_df = pd.read_csv(r"data/scraped-data/druid_stones-scrape.csv")
druid_stones_scrape_df[['url', 'star_ratings', 'suggested_ratings', 'on_to_do_lists', 'ticks']].to_sql('druid_stones_scrape', engine, index=True) # Create the database

happy_boulders_scrape_df = pd.read_csv(r"data/scraped-data/happy_boulders-scrape.csv")
happy_boulders_scrape_df[['url', 'star_ratings', 'suggested_ratings', 'on_to_do_lists', 'ticks']].to_sql('happy_boulders_scrape', engine, index=True) # Create the database

sad_boulders_scrape_df = pd.read_csv(r"data/scraped-data/sad_boulders-scrape.csv")
sad_boulders_scrape_df[['url', 'star_ratings', 'suggested_ratings', 'on_to_do_lists', 'ticks']].to_sql('sad_boulders_scrape', engine, index=True) # Create the database

joshua_tree_scrape_df = pd.read_csv(r"data/scraped-data/joshua_tree-scrape.csv")
joshua_tree_scrape_df[['url', 'star_ratings', 'suggested_ratings', 'on_to_do_lists', 'ticks']].to_sql('joshua_tree_scrape', engine, index=True) # Create the database

In [3]:
buttermilks_scrape_df = pd_sql.read_sql("SELECT * FROM buttermilks_scrape", connection)
buttermilks_scrape_df.head()

,index,url,star_ratings,suggested_ratings,on_to_do_lists,ticks
0,0,https://www.mountainproject.com/route/10627753...,30,5,8,52
1,1,https://www.mountainproject.com/route/10725330...,14,4,8,30
2,2,https://www.mountainproject.com/route/10593616...,12,3,4,28
3,3,https://www.mountainproject.com/route/11671544...,1,1,0,1
4,4,https://www.mountainproject.com/route/11424113...,2,1,0,2

In [4]:
joshua_tree_scrape_df = pd_sql.read_sql("SELECT * FROM joshua_tree_scrape", connection)
joshua_tree_scrape_df.head()

,index,url,star_ratings,suggested_ratings,on_to_do_lists,ticks
0,0,https://www.mountainproject.com/route/10664937...,69,13,208,159
1,1,https://www.mountainproject.com/route/10579807...,5,2,10,4
2,2,https://www.mountainproject.com/route/10579807...,5,2,4,4
3,3,https://www.mountainproject.com/route/11618776...,2,1,1,2
4,4,https://www.mountainproject.com/route/10664144...,4,3,10,6